name: CI CD

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

jobs:
  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        pytorch-version: [1.9, '1.10', 1.11]
        cuda-version: [10.2, 11.3]
        include:
          - cuda-version: 10.2
            cuda-arch-list: "3.7 5.0 6.0 6.1 6.2 7.0 7.2 7.5+PTX"
            gcc-version: 8
          - cuda-version: 11.3
            cuda-arch-list: "3.7 5.0 6.0 6.1 6.2 7.0 7.2 7.5 8.0 8.6+PTX"
            gcc-version: 10
        exclude:
          - pytorch-version: 1.9
            cuda-version: 11.3 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            PYTORCH_VERSION=${{ matrix.pytorch-version }}
            CUDA_VERSION=${{ matrix.cuda-version }}
            CUDA_ARCH_LIST=${{ matrix.cuda-arch-list }}
            GCC_VERSION=${{ matrix.gcc-version }}
          context: ./manylinux
          tags: torchextentionbuilder/manylinux-test:py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}-cu${{ matrix.cuda-version }}
          push: ${{ github.ref == 'refs/heads/main' }}
  
  build-test-package:
    name: Build Test Package
    needs: build-images
    uses: charliebudd/torch-extention-builder/.github/workflows/build-pytorch-extention-wheels.yml
    with:
      working-directory: test_extention
      build-command: python setup.py bdist_wheel
      python-versions: "[3.6, 3.7, 3.8]"
      pytorch-versions: "[1.9, '1.10', 1.11]"
      cuda-versions: "[10.2, 11.3]"
      image-repo: "manylinux-test"
       
  test-built-package:
    name: Test Built Package
    needs: build-test-package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        pytorch-version: [1.9, '1.10', 1.11]
        cuda-version: [10.2, 11.3]
        exclude:
          - pytorch-version: 1.9
            cuda-version: 11.3 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install Test Requirements
        run: |
          python -m pip install -U --force-reinstall pip
          python -m pip install numpy torch==${{ matrix.pytorch-version }} -f https://download.pytorch.org/whl/cu$(echo ${{ matrix.cuda-version }} | sed 's/\.//')/torch_stable.html
        
      - name: Download Cached Wheels
        uses: actions/download-artifact@v3
        with:
          name: final-wheels
          path: final-wheels
          
      - name: Install Package From Cached Wheels
        run: python -m pip install final-wheels/*cp$(echo ${{ matrix.python-version }} | sed 's/\.//')*.whl

      - name: Run Test
        run: python test_extention/test.py
       
  tests-passed:
    name: Tests Passed
    needs: test-built-package
    runs-on: ubuntu-latest
    steps:
      - name: Tests Passed
        run: echo "Tests Passed"
        
  publish-images:
    name: Publish Images
    needs: test-built-package
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        pytorch-version: [1.9, '1.10', 1.11]
        cuda-version: [10.2, 11.3]
        exclude:
          - pytorch-version: 1.9
            cuda-version: 11.3 
    steps:
      - name: Copy Images From Test Repository
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/torchextentionbuilder/manylinux-test:py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}-cu${{ matrix.cuda-version }}
          dst: docker.io/torchextentionbuilder/manylinux:py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}-cu${{ matrix.cuda-version }}-${GITHUB_REF/refs\/tags\//}
