name: Publish Docker Images

on:
  push:
    branches: [main]
    paths: [manylinux]
  pull_request:
    paths: [manylinux]

jobs:
  build-and-push-docker-image:
    name: Building manylinux:py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}-cu${{ matrix.cuda-version }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        pytorch-version: [1.9, 1.10]
        cuda-version: [10.2, 11.3]
        include:
          - cuda-version: 10.2
            cuda-arch-list: "6.0 6.1 6.2 7.0 7.2 7.5+PTX"
            gcc-version: 8
          - cuda-version: 11.3
            cuda-arch-list: "6.0 6.1 6.2 7.0 7.2 7.5 8.0 8.6+PTX"
            gcc-version: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            PYTORCH_VERSION=${{ matrix.pytorch-version }}
            CUDA_VERSION=${{ matrix.cuda-version }}
            CUDA_ARCH_LIST=${{ matrix.cuda-arch-list }}
            GCC_VERSION=${{ matrix.gcc-version }}
          context: ./manylinux
          tags: torchextentionbuilder/manylinux:py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}-cu${{ matrix.cuda-version }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
