name: Publish Docker Images

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Building manylinux:py${{ matrix.python }}-cu${{ matrix.cuda }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        cuda: [10.2, 11.3]
        python: [3.6, 3.7, 3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            CUDA_VERSION=${{ matrix.cuda }}
          context: ./manylinux
          tags: torchextentionbuilder/manylinux:py${{ matrix.python }}-cu${{ matrix.cuda }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
