name: Sub Workflow

on: workflow_call

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Get Tag
        id: get-tag
        run: |
          REQUEST_BASE=https://api.github.com/repos/${{ github.repository }}/actions
          JOBS_REQUEST=$REQUEST_BASE/runs/${{ github.run_id }}/jobs
          AUTH=username:${{ secrets.GITHUB_TOKEN }}
          HEADER="Accept: application/vnd.github.v3+json"
          JOBS=$(curl -u $AUTH -H $HEADER $JOBS_REQUEST -L --output -)
          JOB_IDS=$(echo $JOBS | sed 's/\"id\": /\n"id\": /g' | cut -d ',' -f1 | grep "\"id\": " | sed 's/\"id\": //g')
          LOGS_REQUEST=$REQUEST_BASE/jobs/${JOB_IDS[0]}/logs
          LOGS=$(curl -u $AUTH -H $HEADER $LOGS_REQUEST -L --output -)
          DTAG=$(echo $LOGS | grep -o "Job defined at: charliebudd/torch-extension-builder/.github/workflows/sub-workflow.yml@refs/.*/.*" | sed 's:.*/::')
          TAG=v8
          if [[ $TAG == main ]] || [[ $TAG =~ v[0-9] ]]; then
              echo "::set-output name=tag::-$TAG"
          else
              echo "::set-output name=tag::"
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: echo ${{needs.setup.outputs.tag}}
