name: Sub Workflow

on: workflow_call

jobs:
  get_tag:
    name: Get Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          echo ${{ github.job }}
          REQUEST_BASE=https://api.github.com/repos/${{ github.repository }}/actions
          JOBS_REQUEST=$REQUEST_BASE/runs/${{ github.run_id }}/jobs
          AUTH=username:${{ secrets.GITHUB_TOKEN }}
          HEADER="Accept: application/vnd.github.v3+json"
          JOBS=$(curl -u $AUTH -H $HEADER $JOBS_REQUEST -L --output -)
          JOB_IDS=$(echo $JOBS | sed 's/\"id\": /\n"id\": /g' | cut -d ',' -f1 | grep "\"id\": " | sed 's/\"id\": //g')
          LOGS_REQUEST=$REQUEST_BASE/jobs/${JOB_IDS[0]}/logs
          LOGS=$(curl -u $AUTH -H $HEADER $LOGS_REQUEST -L --output -)
          echo $LOGS
