name: Win Test

on: push

jobs:
  build-wheels:
    name: Build Wheels
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        pytorch-version: [1.9, '1.10', 1.11, 1.12]
        cuda-version: [10.2, 11.3, 11.6]
        include:
          - cuda-version: 10.2
            cuda-arch-list: "3.7 5.0 6.0 6.1 6.2 7.0 7.2 7.5+PTX"
            gcc-version: 8
          - cuda-version: 11.3
            cuda-arch-list: "3.7 5.0 6.0 6.1 6.2 7.0 7.2 7.5 8.0 8.6+PTX"
            gcc-version: 10
          - cuda-version: 11.6
            cuda-arch-list: "3.7 5.0 6.0 6.1 6.2 7.0 7.2 7.5 8.0 8.6+PTX"
            gcc-version: 10
        exclude:
          - python-version: 3.6
            pytorch-version: 1.11
          - python-version: 3.6
            pytorch-version: 1.12
          - pytorch-version: 1.9
            cuda-version: 11.3
          - pytorch-version: 1.9
            cuda-version: 11.6 
          - pytorch-version: '1.10'
            cuda-version: 11.6 
          - pytorch-version: 1.11
            cuda-version: 11.6 
    steps:
      - name: Install Python
        run: install-python.bat

      - name: Install Cuda
        run: install-cuda.bat

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Wheels
        working-directory: test_extention
        run: python setup.py install
